[package]
name = "pbc"
version = "0.1.0"
authors = ["andelf <andelf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"

pbc-sys = { path = "../pbc-sys" }